#!/usr/bin/env bash
# Commands to install Nginx on Web-Sever-01

# Updating Packages before making Installations
sudo apt-get update
sudo apt-get install nginx -y

echo "server {
      listen 80 defult_server;
      listen [::]:80 defylt_server;
      
      root /var/www/html;
      index index.html;
      
      server_name _;
      
      
      location / {
              return 200 'Hello World!';
              add_header Content-Type text/plain;
}
}" | sudo tee /etc/nginx/sites-available/defult



sudo ufw allow 'nginx HTTP'
sudo service nginx restart 
curl http://localhosts/
