#!/usr/bin/env bash
# Commands to install Nginx on Web-Sever-01

# Updating Packages before making Installations
# Install nginx
apt-get update
apt-get install -y nginx

# Configure nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80 default_server\;/' /etc/nginx/sites-available/default

# Add custom response to nginx config 
echo 'server {
        listen 80 default_server;
        location / {
                return 200 "Hello World!\n";
        }
}' > /etc/nginx/sites-available/default

# Restart nginx without systemctl
nginx -s reload
