#!/usr/bin/env bash

# This script is displaying "Best School" 10 times

# Initialize a counter
count=0

# Use an until loop to repeat the message until the counter reaches 10
until [ $count -ge 10 ]; do
  echo "Best School"
  ((count++))  # Increment the counter
done
