#!/usr/bin/env bash
#we can do this while echo print 
hour=0
minute=1

while [ "$hour" -le 12 ] && [ "$minute" -le 59 ]; do
  echo "Hour: $hour"
  while [ "$minute" -le 59 ]; do
    echo "$minute"
    minute=$((minute + 1))
  done
  minute=1
  hour=$((hour + 1))
done | head -n 70

